# SCORIA AI Production Configuration
# -----------------------------------
# Environment: Solana MainNet
# Security: HSM/KMS Integrated | PCI-DSS & SOC2 Compliant

[environment]
mode = "prod"
log_level = "info"
enable_hot_reload = false
fail_fast = true
clean_on_exit = true
data_retention_days = 365

[network]
solana_rpc = "https://ssc-dao.genesysgo.net"
local_rpc_port = 8899  # Reserved for health checks
ipfs_gateway = "https://ipfs.scoria.network"
enable_local_testnet = false
rpc_timeout = 10
max_retries = 3
retry_backoff_ms = 1000

[paths]
model_cache = "/var/lib/scoria/models"
keypair_store = "vault://scoria-keys"
log_directory = "/var/log/scoria"
snapshots = "/opt/scoria/snapshots"
audit_logs = "/var/audit/scoria"

[dependencies]
anchor_version = "0.29.0"  # Immutable in prod
solana_sdk = "1.16.12"     # Pinned version
cuda_toolkit = "12.2"      # Certified driver 535.104.05
onnxruntime = "1.16.3"     # Signed build

[accounts.prod]
validator = "SCORIAv2Validator11111111111111111111111111"
fee_payer = "vault://scoria-fee-payer"
emergency_multisig = "7shwBm...."  # 3/5 multisig

[features]
enable_gpu = true
enable_zkp_prover = true
enable_local_inference = true
enable_debug_apis = false
enable_telemetry = true

[security.prod]
allow_unsigned = false
insecure_http = false
whitelist_origins = ["https://*.scoria.network"]
unencrypted_storage = false
tls_version = "1.3"
hsm_slot = 0
kms_arn = "arn:aws:kms:us-west-2:123456789012:key/abcd1234"

[monitoring]
prometheus_port = 9273  # Authenticated endpoint
grafana_port = 3000     # Behind VPN
tracing_endpoint = "https://otel.scoria.network"
sentry_dsn = "https://abc123@sentry.scoria.net/7"
datadog_api_key = "vault://datadog-key"

[autoscaling]
min_gpu_nodes = 3
max_gpu_nodes = 12
target_gpu_util = 70
scale_cooldown_sec = 300

[database]
postgres_master = "postgres://prod-user:***@pg-master.scoria.net:5432"
postgres_replica = "postgres://prod-user:***@pg-replica-zone2.scoria.net:5432"
redis_cluster = "redis://:***@redis-cluster.scoria.net:6379"
connection_pool_size = 50
query_timeout_ms = 5000

[backup]
s3_bucket = "scoria-vault"
s3_region = "us-west-2"
snapshot_interval = 3600  # 1 hour
retention_days = 35
emergency_wipe_protocol = "red_key"  # Requires 3/5 council approval

[zkp]
groth16_trusted_setup = "aws-nitro://scoria-trusted-setup"
max_constraints = 100000000
proof_timeout_sec = 30
circuit_cache_size = 50

[gpu_config]
max_memory_utilization = 0.85
compute_mode = "exclusive"
fallback_to_cpu = false
enable_tensor_cores = true
mixed_precision = true
cuda_graphs = true

[compliance]
gdpr_mode = true
data_residency = "REGION_US"
sanctions_filter = true
ofac_api_endpoint = "https://sanctions.scoria.net/v1/check"

[disaster_recovery]
hot_standby_region = "eu-central-1"
failover_ttl = 60  # Seconds
geo_redundant_storage = true

[alerting]
pagerduty_key = "vault://pagerduty-key"
slack_webhook = "vault://slack-alerts"
critical_alert_recipients = ["sre@scoria.network"]

[rate_limiting]
api_requests_per_second = 1000
inference_queue_size = 500
priority_levels = 3  # Platinum/Gold/Silver

[maintenance]
weekly_window = "Sun 01:00-03:00 UTC"
critical_update_override = true

[legal]
terms_hash = "bafybeidfg...."  # IPFS CID
privacy_policy_version = "2.3.1"
